language: csharp
solution: Matrix.sln
os: linux
mono: none
dist: focal
dotnet: 5.0
install:
  - dotnet restore
script:
  - dotnet build
  - dotnet test
global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
